// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'models/todo_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7591326133564823718),
    name: 'TodoItem',
    lastPropertyId: const obx_int.IdUid(8, 8654901854306801776),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5079290158015726683),
        name: 'dbId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6170303483573153873),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5140922588276922547),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3681742437002594878),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 494580473604007620),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1120771607537725014),
        name: 'dueDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4562152692702225236),
        name: 'isDone',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9052759399062847881),
        name: 'priorityValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8654901854306801776),
        name: 'statusValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7591326133564823718),
    lastIndexId: const obx_int.IdUid(1, 5140922588276922547),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TodoItem: obx_int.EntityDefinition<TodoItem>(
      model: _entities[0],
      toOneRelations: (TodoItem object) => [],
      toManyRelations: (TodoItem object) => {},
      getId: (TodoItem object) => object.dbId,
      setId: (TodoItem object, int id) {
        object.dbId = id;
      },
      objectToFB: (TodoItem object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(9);
        fbb.addInt64(0, object.dbId ?? 0);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.dueDate?.millisecondsSinceEpoch);
        fbb.addBool(5, object.isDone);
        fbb.addInt64(6, object.priorityValue);
        fbb.addInt64(7, object.statusValue);
        fbb.finish(fbb.endTable());
        return object.dbId ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dueDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final dbIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final dueDateParam = dueDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dueDateValue, isUtc: true);
        final isDoneParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object =
            TodoItem(
                dbId: dbIdParam,
                id: idParam,
                title: titleParam,
                description: descriptionParam,
                dueDate: dueDateParam,
                isDone: isDoneParam,
              )
              ..priorityValue = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                16,
                0,
              )
              ..statusValue = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                18,
                0,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TodoItem] entity fields to define ObjectBox queries.
class TodoItem_ {
  /// See [TodoItem.dbId].
  static final dbId = obx.QueryIntegerProperty<TodoItem>(
    _entities[0].properties[0],
  );

  /// See [TodoItem.id].
  static final id = obx.QueryStringProperty<TodoItem>(
    _entities[0].properties[1],
  );

  /// See [TodoItem.title].
  static final title = obx.QueryStringProperty<TodoItem>(
    _entities[0].properties[2],
  );

  /// See [TodoItem.description].
  static final description = obx.QueryStringProperty<TodoItem>(
    _entities[0].properties[3],
  );

  /// See [TodoItem.dueDate].
  static final dueDate = obx.QueryDateProperty<TodoItem>(
    _entities[0].properties[4],
  );

  /// See [TodoItem.isDone].
  static final isDone = obx.QueryBooleanProperty<TodoItem>(
    _entities[0].properties[5],
  );

  /// See [TodoItem.priorityValue].
  static final priorityValue = obx.QueryIntegerProperty<TodoItem>(
    _entities[0].properties[6],
  );

  /// See [TodoItem.statusValue].
  static final statusValue = obx.QueryIntegerProperty<TodoItem>(
    _entities[0].properties[7],
  );
}
